#include <iostream>
#include <string.h>
#include <rpc/rpc.h>        //* standard RPC include file */

#include <stdlib.h>
#include <arpa/inet.h>
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <string.h>
#include <sys/wait.h>
#include <netdb.h>
#include <unistd.h>

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>

#define PORT   1976
#define BUFLEN 2076

extern "C"{
#include "server_verifyxdr.h"
}                        //* this file is generated by rpcgen */
using namespace std;

int N, L, M;
int counter=0;
bool isConnectedToUDP = false;
bool stringReceived = false;
size_t totalStringLength;  

int createdSocket = 0;
int bytesReceived = 0;
char receiveBuffer[256];
char S[] = {};

void connectToUDP(){
	cout << "ATTEMPTING TO CONNECT VIA UDP" << endl;
	memset(receiveBuffer, '0', sizeof(receiveBuffer));
	struct sockaddr_in serv_addr;

	/* Create a socket first */
    if ((createdSocket = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
        cout << "ERROR CREATING SOCKET" << endl;
    } else{
    	cout << "SOCKET CREATED SUCCESSFULLY" << endl;
    }

    /* Initialize sockaddr_in data structure */
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_port = htons(5000); // port
    serv_addr.sin_addr.s_addr = inet_addr("127.0.0.1");

    /* Attempt a connection */
    if (connect(createdSocket, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) == -1) {
    	cout << "ERROR CONNECTING TO SOCKET" << endl;
    } else isConnectedToUDP = true;
}

char *receiveViaUDP(){
	while ((bytesReceived = recv(createdSocket, receiveBuffer, 256, 0)) > 0) {
        printf("Bytes received %d\n", bytesReceived);    
        printf("%s \n", receiveBuffer);
        strncpy(S, receiveBuffer, totalStringLength);
        cout << "STRING: " << S << endl;
    }

    if (strlen(S) == totalStringLength) {
    	stringReceived = true;
        cout << "STRING: " << S << " - TRANSFERRED SUCCESSFULLY" << endl;
    } 

    return S;
}

char **rpc_getseg_1_svc(server_segment *xdrm, struct svc_req *s) {
	static char *seg = (char*) malloc(L+1);

	if (!isConnectedToUDP) {
		connectToUDP();
        return(NULL);

	} else {
		if (!stringReceived) {
			seg = receiveViaUDP();
			return(&seg);
		} else {
			if (xdrm->seg == -1) {
				static char *seq = S;
				return(&seq);
			}

			size_t start = counter * L;

			if (start >= sizeof(S)) {
				cout << "END" << "\n";
				seg = (char *) "-";
				return(&seg);
			} 

			strncpy(seg, S+start, L);
			seg[L]='\0';
			cout << xdrm->seg << " START: " << start <<" REQUESTED: " << seg << "\n";
			counter++;
			return(&seg);
		}
	}
	return NULL;
}

char **rpc_initverifyserver_1_svc(server_verifyxdr *xdrm, struct svc_req *s) {
    static char *ptr = (char *)"Verify server initialzied"; 
	N = xdrm->N;
	L = xdrm->L;
	M = xdrm->M;

	totalStringLength = M * L;

    return(&ptr);
}
