#include <iostream>
#include <string.h>
#include <rpc/rpc.h>        //* standard RPC include file */

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include <arpa/inet.h>
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <string.h>
#include <sys/wait.h>
#include <netdb.h>
#include <unistd.h>

#define PORT   1976
#define BUFLEN 2076

extern "C"{
#include "server_verifyxdr.h"
}                        //* this file is generated by rpcgen */
using namespace std;

int N, L, M;
int counter=0;
char S[] = {"abcaabcaabcaabcaabca"};

char **rpc_getseg_1_svc(server_segment *xdrm, struct svc_req *s) {
	int start = counter*L;
	static char *seg = (char*) malloc(L+1);

	if (start >= strlen(S)) {
		cout << "END" << "\n";
		seg = (char *) "-";
		return(&seg);
	} 

	strncpy(seg, S+start, L);
	seg[L]='\0';
	cout << xdrm->seg << " START: " << start <<" REQUESTED: " << seg << "\n";
	counter++;
	return(&seg);
}

char **rpc_initverifyserver_1_svc(server_verifyxdr *xdrm, struct svc_req *s) {
    static char *ptr = (char *)"Verify server initialzied"; 
	N = xdrm->N;
	L = xdrm->L;
	M = xdrm->M;
    // cout << "Message from client: "<< xdrm->string_arg << "\n";
     
//     struct sockaddr_in si_me, si_other;
    
//     int soc;
//     char rcvBuf[BUFLEN];
//     char sndBuf[BUFLEN];
//     char strIP[BUFLEN];
//     char myStr[BUFLEN];
//     int slen = sizeof(si_other);
    
//     soc = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
//     if (soc == -1){
//         exit(0);
//     }
//     else
//         printf("UDP Socket created successfully.\n");
    
//     memset((char *) &si_me, 0, sizeof(si_me));
//     si_me.sin_family = AF_INET;
//     si_me.sin_port = htons(PORT);
//     si_me.sin_addr.s_addr = htonl(INADDR_ANY);
    
//     int retVal = bind(soc, (struct sockaddr*)&si_me, sizeof(si_me));
//     if (retVal == -1){
//         exit(0);
//     }
//     else
//         printf("UDP Socket bound successfully.\n");
    
//     while (1)
//     {
//         printf("Waiting to receive a message...\n");
//         retVal = recvfrom(soc, rcvBuf, BUFLEN, 0, (struct sockaddr *)&si_other, (socklen_t*)&slen);
//         if (retVal == -1){
//             exit(0);
//         }
        
//         printf("Received packet from %s:%d\nMessage: %s\n\n", inet_ntoa(si_other.sin_addr), ntohs(si_other.sin_port), rcvBuf);
        
// /*        gets(myStr);
//         int len = sprintf(sndBuf, "%s\n%s", rcvBuf, myStr);
        
//         gets(strIP);
//         si_other.sin_port = htons(PORT);
//         inet_aton(strIP, &si_other.sin_addr);
        
//         sendto(soc, sndBuf, len, 0, (struct sockaddr *)&si_other, slen);
// */
//          }
    
//     close(soc);
     
    return(&ptr);
}
