#include <iostream>
#include <string.h>
#include <rpc/rpc.h>        //* standard RPC include file */

#include <stdlib.h>
#include <unistd.h>
#include <netdb.h>
#include <sys/types.h> 
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/uio.h>

extern "C"{
#include "server_appendxdr.h"
}                        //* this file is generated by rpcgen */
using namespace std;

string S;
int currStringLength = 0;
int totalStringLength;
bool isListening = false;

int listenSocket = 0;
int connectedSocket = 0;
struct sockaddr_in serv_addr;
char sendBuff[1025];
int numrv;

void setupUDP() {
  
  if ((listenSocket = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
    cout << "ERROR CREATING SOCKET" << endl;
  }

  memset(&serv_addr, '0', sizeof(serv_addr));
  memset(sendBuff, '0', sizeof(sendBuff));

  serv_addr.sin_family = AF_INET;
  serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
  serv_addr.sin_port = htons(5000);

  if (bind(listenSocket, (struct sockaddr*) &serv_addr, sizeof(serv_addr)) == -1) {
    cout << "ERROR: ON BIND" << endl;
  }

  if (listen(listenSocket, 10) == -1) {
    cout << "ERROR ON LISTENING" << endl;
  } else isListening = true;    
}

void transferViaUDP() {
  cout << "INSIDE UDP ACCEPT" << endl;
  while(1) {

    connectedSocket = accept(listenSocket, (struct sockaddr*) NULL, NULL);
    size_t messageLength = S.length();

    while(1) {    
      if (send(connectedSocket, S.c_str(), messageLength, 0) < 0) {
        cout << "ERROR ON FILE TRANSFER" << endl;
      } else {
        cout << "FILE SENT SUCCESSFULLY" << endl;
        close(connectedSocket);
        sleep(1);
        break;
      }
    }
  }
}
  
char **rpc_initappendserver_1_svc(server_appendxdr *xdrm, struct svc_req *s) {
  static char *ptr = (char *)"Append server initialized"; /* must be static */

	totalStringLength = xdrm->M * xdrm->L;
  cout << "Message from client: "<< xdrm->c0 << xdrm->c1 << xdrm->c2 << "\n";
     
  return(&ptr);
}

int *rpc_append_1_svc(server_letter *xdrm, struct svc_req *s) {
  static int retVal = 0;
  cout << "INSIDE rpc_append_1_svc" << endl;

  if (currStringLength != totalStringLength) {
    S += xdrm->letter;
    currStringLength++;
    cout << "LETTER: " << xdrm->letter << " | STRING LENGTH IS: " << currStringLength << " | STRING: " << S.c_str() << endl;
 	  if (currStringLength == totalStringLength) {
      cout << "TOTAL STRING LENGTH REACHED" << endl;
      retVal = -1;
      return(&retVal);
    }
  } else {
      cout << "STRING HAS BEEN COMPLETED: " << S.c_str() << endl;
      retVal = -1;
      //START UDP SETUP
      if (!isListening) {
        setupUDP();
        return(&retVal);
      } else {
        transferViaUDP();
        return(&retVal);
      }
 	}

  return(&retVal);
}
